Adding data from db seed
YaponEran/testGuru pull request #5
Opened 2020-11-20 10:58 UTC by YaponEran

2020-11-21 13:47 UTC, VidgarVii requested changes

2020-11-21 13:47 UTC, VidgarVii commented on db/seeds.rb
> +])
в сидах следует использовать bang! методы (create!). На случай если что-то пойдет не так, то выбросилась ошибка. А сейчас если кто-то не создастся, то ты этого не узнаешь

2020-11-21 13:47 UTC, VidgarVii commented on db/seeds.rb
> +])
Прежде чем что-то записывать сидами, надо убедиться, если ли данные в таблице. В данный момент. Если 10 раз запустить сиды, то создадутся 10 юзеров, 10 категорий и т.д. И в целом данные будут не корректные.

2020-11-21 13:47 UTC, VidgarVii commented on db/seeds.rb
> +answers = Answer.create([
переменная answers ни где не используется. Можно не записывать данные в память.

2020-11-21 13:47 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
в ДЗ нет задачи создать ассоциации. Следует выполнять только задание в рамках поставленной задачи. Ассоциации будут дальше по уроку.

2020-11-21 13:47 UTC, VidgarVii commented on app/models/user.rb
> +  def usert_test_level(level)
название метода. не совсем подходящие да и с ошибкой. Ты уже обращаешься к экземпляру класса юзер. юзер#юзер_ какая то тавтология.
Лучше обозвать что то типо pass_tests_by_level()

2020-11-21 13:47 UTC, VidgarVii commented on app/models/user.rb
> +    tests.where(level: level)
без ассоциаций код будет другим. Надо еще потренироваться составлять sql запросы. За одно поймешь как строятся отношения м/у моделями. А потом уже перепишешь красиво согласно ОРМ

2020-11-21 13:47 UTC, VidgarVii commented on app/models/test.rb
> +    joins(:category).where(categories: {title: categor_title})
в этом задании нет у нас ассоциаций

2020-11-23 08:50 UTC, closed without merging

2020-11-23 08:50 UTC, YaponEran commented
bugs